Dev/sds1072cml
pymeasure/pymeasure pull request #1080
Opened 2024-03-29 18:51 UTC by fthouin

First draft of a module to control the Siglent SDS1072CML oscilloscope

_ Unit tests are still lacking
_ the module is usable but awkward (especially the trigger setting)

2024-04-08 16:30 UTC, BenediktBurger commented on tests/instruments/siglenttechnologies/test_siglent_sds1072cml.py
Thanks for adding tests. However, please see the [writing tests](https://pymeasure.readthedocs.io/en/latest/dev/adding_instruments/tests.html) section of our documentation.

The `test_instrument.py` file contains protocol tests (without a device), while `test_instrument_with_device` contains tests with an actual device. For a device test, we have a fixture, which allows to define the resource name as a command line parameter.

2024-04-08 16:30 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +# Copyright (c) 2013-2023 PyMeasure Developers
```suggestion
# Copyright (c) 2013-2024 PyMeasure Developers
```
I guess you started last year.

2024-04-13 19:16 UTC, fthouin commented
Hi Benedict,

Thanks for the feedback, I have finalized the control of the instrument (trigger and all)

I would now like to add tests using [the test generator](https://pymeasure.readthedocs.io/en/latest/dev/adding_instruments/tests.html#test-generator). However, when invoking `from pymeasure.generator import Generator` I get a `ModuleNotFoundError: No module named 'pymeasure.generator'` error.

Is this feature still supported or have I forgotten to configure something?

Thanks for your help!

2024-04-15 08:39 UTC, BenediktBurger commented
> I would now like to add tests using [the test generator](https://pymeasure.readthedocs.io/en/latest/dev/adding_instruments/tests.html#test-generator). However, when invoking `from pymeasure.generator import Generator` I get a `ModuleNotFoundError: No module named 'pymeasure.generator'` error.

I do not know by heart, whether the test generator is already part of the latest release or not. Do you have pymeasure installed as a release or from github?
The test generator is already part of the master branch for some time, but not very long.
Do you find the file `pymeasure.generator.py` in your branch?
If not, you can merge the current master branch into your branch (which you have to do anyways, in order to resolve the authors.txt conflict.

2024-04-30 08:19 UTC, BenediktBurger requested changes
A few comments how to improve your code, which is mainly code style according to python standards.
For more information see https://peps.python.org/pep-0257/

2024-04-30 08:19 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        "Sets or gets the vertical sensitivity of a channel.",
Docstrings in general should be in imperative mode (so "Set or Get"...)

We in pymeasure use "Control" for "Set or get" as the first word of a `control`. For a `measurement` it is "Measure" or "Get" and for a `setting` it is "Set".

```suggestion
        "Control the vertical sensitivity of a channel.",
```

2024-04-30 08:19 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        "Sets and gets the channel coupling mode. (see UM p. 35)",
The reference to the user manual is not as useful for those, who do not have it. It is better, if you add the options ("DC" and "AC").
```suggestion
        "Sets and gets the channel coupling mode to "AC" or "DC". (see UM p. 35)",
```

2024-04-30 08:19 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        return:
A docstring should be in imperative mode. The first sentence should be separated by the rest by an empty line:
```suggestion
        Return the waveforms displayed in the channel.

        return:
```

2024-04-30 08:19 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +    def getWaveform(self):
normally for python the style is `get_waveform` for methods.

2024-04-30 08:19 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +    def getDesc(self):
```suggestion
    def get_desc(self):
```

2024-04-30 08:19 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +class TriggerChannel(Channel):
Two empty lines between definitions outside of classes, please.
```suggestion


class TriggerChannel(Channel):
```

2024-04-30 08:19 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +    def getLevel(self):
One empty line between class definitions, please.
```suggestion

    def getLevel(self):
```

2024-04-30 08:19 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +            **kwargs
Please state, whether the device supports SCPI (in this case inherit `SCPIMixin` before `Instrument`) or not (in this case set `includeSCPI=False`).

2024-07-06 22:59 UTC, fthouin commented on tests/instruments/siglenttechnologies/test_siglent_sds1072cml.py
I merged the master branch into my fork and used the Generator to make a test file. Seems like it is rather large since I called a waveform readout during the test generation. Let me know if there is a smarter way to do this. Thanks for your patience and your help!

2024-07-09 11:29 UTC, BenediktBurger requested changes
Thanks for your rework of the code.
Here another set of comments.

Please make sure, that the tests pass (either fixing the test, if it was wrong, or the code)
Regarding formatting of the code, there are tools, which show linting (spyder, pycharm, visual studio code can show linting errors) and there are even tools, which can reformat the code (only how it is shown, not the functionality), for example ruff, black, darker...
I personally use [ruff](https://docs.astral.sh/ruff/) - in my case as a plugin to visual studio code.

2024-07-09 11:29 UTC, BenediktBurger commented on tests/instruments/siglenttechnologies/test_siglent_sds1072cml.py
Thanks for adding tests.

The waveform tests are really large.
Would it be possible to use a waveform with less data points (let's say around 10-20 values)?

2024-07-10 15:26 UTC, fthouin commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        rawWaveform=list(struct.unpack_from('%db'%descriptorDictionnary["numDataPoints"],response,offset=descriptorDictionnary["descriptorOffset"]))
Ran Ruff on the document. It seems to have fixed the issues raised.

2024-07-27 23:28 UTC, fthouin commented on tests/instruments/siglenttechnologies/test_siglent_sds1072cml.py
Sure is. I added a 20 point waveform test and it seems to work pretty well.

2024-07-27 23:28 UTC, fthouin commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +from pymeasure.instruments.validators import strict_discrete_range,truncated_discrete_set,strict_range,truncated_range
Learned the joys of Ruff! All tests are green.

2024-07-29 07:55 UTC, BenediktBurger requested changes
Mainly minor issues to address (naming, a few typos).

Thanks for your patience.

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        print(descriptorDictionnary)
Why a print command? Did you use it for debugging?

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
>          - numDataPoints: the number of poitns in the waveform
```suggestion
        - numDataPoints: the number of points in the waveform
```

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
>          dict: A dictionnary with the keys:
```suggestion
        dict: A dictionary with the keys:
```

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        descriptorDictionnary = {"sparsing": sparsing, "numDataPoints": number, "firstPoint": first}
```suggestion
        descriptor_dictionary = {"sparsing": sparsing, "numDataPoints": number, "firstPoint": first}
```
First, the word _dictionary_ does not contain two times _n_.
Second, python recommendation is to use an underscore to separate words in a variable (or method) name.
(btw. Classes use CamelCase)

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        set_process=lambda v: "%.2eV" % v,
Why don't you put the set_process logic into the set_command itself?
```suggestion
        "C{ch}:VDIV %.2eV",
        "Control the vertical sensitivity of a channel in V/divisions.",
        validator=truncated_range,
        values=[2e-3, 10],
        get_process=lambda v: float(v.split(" ", 1)[-1][:-1]),
```

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        self.write(command)
Just a suggestion:
you can combine these two lines into one, as it won't get overly complex.
```suggestion
        self.write( "C{ch}:WF? ALL")
```

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +    triggerConfDict = {}
please use snake_case for variables and methods (i.e. all lower caps and separating words with underscores):
```suggestion
    trigger_config_dict
```

Please keep abbreviations consistent (here config for the methods below)

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +    def get_triggerConfig(self):
This is a weird combination of snake_case (underscore) and camelCase (cap): methods in python are typically snake case:
```suggestion
    def get_trigger_config(self):
```

Please do it below as well.

I noticed, that you use camelCase inside your methods as well. There it does not matter that much, as a user does not access them, but for consistency it is better to make everything snake_case.

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +    timeDiv = Instrument.control(
```suggestion
    time_division = Instrument.control(
```

2024-07-29 07:55 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        set_process=lambda v: "%.2eS" % v,
You can use that set_process logic already in the set_command:
```suggestion
        ":TDIV %.2eS",
        "Set the time division to the closest possible value,rounding downwards.",
        validator=truncated_range,
        values=[5e-9, 50],
```

2024-09-06 18:07 UTC, BenediktBurger requested changes
Thanks for your rework. Main issues are the use of `control` and `measurement`, and some code formatting/docstrings.

2024-09-06 18:07 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        set_process=lambda dictIn: (
please rename to `dict_in` for python standards.

2024-09-08 02:58 UTC, fthouin commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +    def get_desc(self, descriptor=None):
Yes there is some complicated binary string interpretation going on I couldn't get to work with a property. I changed the name of the method.

2024-09-08 03:05 UTC, fthouin commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        if (v.split(" ", 1)[-1] in ["Stop", "Ready", "Armed"])
Oooouuuhhhh neet. Thanks!

2024-09-29 18:50 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +    def get_desc(self, descriptor=None):
Sorry for the delay.

With a "plain property" I meant something like:
~~~python
@property
def descriptor(self, descriptor=None):
    return self.get_desc(descriptor=descriptor
~~~

That allows later to call `inst.descriptor` in order to get the descriptor.

Just to show, what I meant.

2024-09-29 19:05 UTC, BenediktBurger approved these changes
Thanks for your rework and your patience.

Only tiny comments remain.

2024-09-29 19:05 UTC, BenediktBurger commented on pymeasure/instruments/siglenttechnologies/siglent_sds1072cml.py
> +        """
Docstrings should have (according to PEP 257) a single sentence in the first line (terminated with a period). Then an empty line, afterwards a summary and/or the parameters.
Also, for sphinx (our documentation generator), you have to start a parameter line with a colon:
```suggestion
        """Stop the scope from doing anything until it has completed the current acquisition.

        :param time: time in seconds to wait for
        """
```

why do you reference the manual (page 146)? is there any relevant information you better shared here?

2024-11-19 03:17 UTC, fthouin commented
@BenediktBurger, is there anything else you would like me to do for this PR?

2024-11-19 09:57 UTC, BenediktBurger approved these changes
Thanks for your patience, waiting for my review as I was very busy.

The only issue left is the ruff linting.

2024-11-19 09:57 UTC, BenediktBurger commented on pyproject.toml
> +select = ["E"]
I suggest to change it to "[extend-select](https://docs.astral.sh/ruff/settings/#lint_extend-select)" in order to keep the default values:
```suggestion
extend-select = ["E"]
```

Or what was your idea about this line?
If it leads to some discussion, we can remove this line in this PR and start an issue, which will lead to another PR.
That way we can merge this PR about an instrument.

2024-11-20 07:51 UTC, merged

2024-11-20 07:51 UTC, BenediktBurger commented
Thanks for your contribution and your patience in this last time.