Add Oxford Instruments Mercury Intelligent Temperature Controller
pymeasure/pymeasure pull request #1198
Opened 2024-12-17 15:54 UTC by JAW90

Add new instrument: Oxford Instruments Mercury Intelligent Temperature Controller (aka iTC).

This instrument is a temperature controller that can read temperature sensors of different types, e.g. silicon diodes, metallic negative thermal coefficient (NTC), positive thermal coefficient (PTC) and also thermocouples. It can also control resistive heaters. I have implemented two channel types, ``Temperature Sensor`` and ``Heater`` to support these two functionalities. There are additional daughterboards that provide further functionality, but these are not implemented (as I don't have any to test).

2025-01-16 10:18 UTC, BenediktBurger requested changes
Thanks for your contribution and sorry for the delay.

Here a few comments, mainly regarding documentation and naming.

2025-01-16 10:18 UTC, BenediktBurger commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +        validator=truncated_range,
Consider a strict range.

Truncated validators don't give feedback about truncation.
a user might set the setpoint to 2100. As no error is raised, he will expect the setpoint to be 2100,not 2000.
With a strict range, a user will get feedback.

2025-01-16 10:18 UTC, BenediktBurger commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +        """Control the control loop temperature setpoint, in Kelvin (in the range
That is, how we propose the text:
```suggestion
        """Control the control loop temperature setpoint, in Kelvin. (float, truncated between 0-2000)
```

If you change the validator, replace truncated to strict

2025-01-16 10:18 UTC, BenediktBurger commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +    loop_heater_pcnt = Channel.control(
Maybe "manual_heater_power"? (the docstring may state that it is a relative power in percent. 

Actually, as it is a float anyways, you could allow the power as a fraction (0.3 instead of 30%).
With set_process / get_process you can do the math. 

at least I recommend to spell percentage, because pcnt is not obvious.

2025-01-16 10:18 UTC, BenediktBurger commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +        validator=truncated_range,
For the validator, see above.

2025-01-16 10:18 UTC, BenediktBurger commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +        """Control whether the temperature ramping function is enabled (``True``) or
As the name is already self evident (therefore we suggest such names), you do not have to spell out, that True enables.
it is sufficient to state, that it is boolean, e. G. With "(bool)" the end.

2025-01-16 10:18 UTC, BenediktBurger commented on tests/instruments/oxfordinstruments/test_mercuryitc.py
Thanks for adding tests.

2025-01-17 10:04 UTC, JAW90 commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +    loop_heater_pcnt = Channel.control(
The instrument displays the heater as a percentage so I think it is good to keep it consistent as a percentage. Naming has been updated for clarity.

2025-01-17 10:06 UTC, JAW90 commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +        validator=truncated_range,
That's a good point. I think this is a valid point for some of the other parameters as well.

2025-01-25 11:53 UTC, BenediktBurger commented on docs/api/instruments/oxfordinstruments/index.rst
> +   MercuryiTC
I was thinking about a subcaption and a new list for a specific group of instruments, but that is not (yet) typical for pymeasure.

What do you think, @bilderbuchi?

2025-04-04 10:27 UTC, JAW90 commented on docs/api/instruments/oxfordinstruments/index.rst
> +   MercuryiTC
I have opted to put the instruments simply in alphabetical order.

2025-04-08 08:49 UTC, BenediktBurger reviewed
A few small comments. Thanks for your work.

2025-04-08 08:49 UTC, BenediktBurger commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +# Copyright (c) 2013-2024 PyMeasure Developers
You did not change the year yet!

2025-04-08 08:49 UTC, BenediktBurger commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +        """Get the control temperature, in Kelvin.""",
What is the "control temperature". Do you mean the temperature setpoint (in this case, please call it temperature_setpoint, for consistency)? Or is ist some reference temperature?

2025-04-11 12:44 UTC, JAW90 commented on pymeasure/instruments/oxfordinstruments/mercuryitc.py
> +        """Get the control temperature, in Kelvin.""",
Yes you are right, it is the temperature setpoint. I will rename it.

2025-04-16 10:09 UTC, BenediktBurger approved these changes
From my side it is ready to be merged.
Please tell me, if you want it merged.

2025-04-16 15:38 UTC, JAW90 commented
Yes, please go ahead and merge. Thanks

2025-04-17 12:44 UTC, merged