Add phase control for Agilent 33500
pymeasure/pymeasure pull request #454
Opened 2021-06-07 13:32 UTC by corna

Tested on an Agilent 33521A but, from the "Agilent 33500 Series Waveform Generator Operating and Service Guide", it should be supported by the whole 33500 family.

2021-06-23 21:03 UTC, msmttchr requested changes
Looks good to me.
Could you please, add yourself to the authors lists at AUTHORS.txt and docs/about/authors.rst?

2021-07-07 17:57 UTC, corna commented
Sorry for the delay, somehow I haven't received the email notification.
Done.

2021-07-07 17:59 UTC, msmttchr commented
Grazie mille :)

Il Mer 7 Lug 2021, 19:57 Nicola Corna ***@***.***> ha scritto:

> Sorry for the delay, somehow I haven't received the email notification.
> Done.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pymeasure/pymeasure/pull/454#issuecomment-875810450>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJAXVWVDJGSIQO7EEAZJGGTTWSIRHANCNFSM46HVWH4A>
> .
>

2021-07-07 18:00 UTC, msmttchr approved these changes

2021-07-07 18:13 UTC, merged