New Instrument Driver: Newport Conex-CC Motion Controller
pymeasure/pymeasure pull request #581
Opened 2022-01-28 10:06 UTC by maederan201

This PR adds a new Instrument Driver: Newport's Conex-CC Motion Controller for Linear Stages

Only the basic functionalities are implemented: Getting/Setting velocity and acceleration, absolute and relative moves (`move_to` and `move_by`) and all functionalities for closed loop operation.

Right now, I'm only using 1 driver but the device offers the possibility to connect multiple drivers and multiple axis (similar to the EPS300 which is already implemented), that's why I want to allow this with the `index` attribute. I was contemplating an implementation of axes similar to the EPS300 but decided against it, as there, the number of axes is hardcoded, but can of course vary on the application. How is such a case generally handled within the pymeasure frame?

2022-02-28 16:25 UTC, bilderbuchi commented on pymeasure/instruments/newport/conexcc.py
> +        self.write(cmd)
`self.write(f'{cmd:f}') should do the same thing and is a more modern string formatting approach. Similar for other occurences.

2022-02-28 16:34 UTC, bilderbuchi requested changes
Thank you, this is looking good. I have some small change requests.
Are you already in the authors files for credit?

> How is such a case generally handled within the pymeasure frame?

We don't have a common API definition for instrument classes yet (see #416). Until that time it's fine to do as you did, your reasoning sounds fine.

2024-01-12 09:18 UTC, BenediktBurger commented
Hey @maederan201 , would you like to finish your almost finished work?

2024-01-16 07:17 UTC, maederan201 commented
Thanks @BenediktBurger for reminding me. I will try and tackle this in the upcoming month. Thanks for the patience

2024-11-21 12:45 UTC, BenediktBurger commented
> Hey @maederan201 , would you like to finish your almost finished work?

2025-06-27 08:15 UTC, BenediktBurger commented
Closed due to lack of response. It might be reopened whenever there is interest.

2025-06-27 08:15 UTC, closed without merging