Keithley6221 - phase marker phase and line
pymeasure/pymeasure pull request #629
Opened 2022-05-30 08:15 UTC by AsafYagoda

waveform_phasemarker_phase - A numerical property that controls the phase of the phase marker.
waveform_phasemarker_line - A numerical property that controls the line of the phase marker.

2022-05-30 12:50 UTC, msmttchr requested changes
@AsafYagoda, thank you very much for your contribution.
I submitted few comments, could You please have a look, if they make sense ?
Please add yourself also to AUTHORS.txt and authors.rst files.

2022-05-30 12:50 UTC, msmttchr commented on pymeasure/instruments/keithley/keithley6221.py
> +        ":SOUR:WAVE:PMAR?", ":SOUR:WAVE:PMAR %s",
```suggestion
        ":SOUR:WAVE:PMAR?", ":SOUR:WAVE:PMAR %g",
```
I guess this is a floating point number, so I propose `%g`, make sense ?

2022-05-30 12:50 UTC, msmttchr commented on pymeasure/instruments/keithley/keithley6221.py
> +        ":SOUR:WAVE:PMAR:OLIN?", ":SOUR:WAVE:PMAR:OLIN %s",
```suggestion
        ":SOUR:WAVE:PMAR:OLIN?", ":SOUR:WAVE:PMAR:OLIN %d",
```
Integer value ?

2022-07-23 11:47 UTC, msmttchr approved these changes
Thanks for your contribution.

2022-08-04 20:13 UTC, bilderbuchi requested changes
LGTM after adding the author name as requested.

2022-08-07 09:02 UTC, AsafYagoda commented
Added myself as a co-author as requested

2022-08-07 10:52 UTC, msmttchr commented
> Added myself as a co-author as requested

@AsafYagoda, I don't see any change in the authors files ?

2022-08-07 15:40 UTC, merged