Dev/agilent e4407b
pymeasure/pymeasure pull request #646
Opened 2022-07-01 01:07 UTC by IanCharboneau

added basic support for the agilent e4407b signal analyzer

2022-08-05 20:22 UTC, bilderbuchi requested changes
Thank you for your contribution! A first round of feedback

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    )
This is unusual as a property, you'd "assign" the segment to delete to the property. Better to have another method (but then name the former `delete_all_segments` for clarity), or handle it with an argument to the above method.

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        """ A boolean property that represents the resolution bandwidth
For boolean properties, you can use the pattern
```
map_values=True,
values={True: 1, False: 0},  # or as appropriate for your device
```
then you can use Python booleans to interact with this.

A good name for boolean properties can be understood as a yes/no question (`output_enabled`) -- here maybe `resolution_bandwidth_auto_enabled`.
Similar below.

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    qp_detector_gain = Instrument.control(
similar reasoning as above, this should probably be a boolean property `qp_detector_gain_enabled`.

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        self.write("*RST")
```suggestion
```
This is already defined in Instrument.reset().

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        """Reset the instrument persistant state vakues to there factory defaults."""
```suggestion
        """Reset the instrument persistent state values to their factory defaults."""
```

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    def persistant_reset(self):
```suggestion
    def persistent_reset(self):
```

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        A command that returns information about the current hardware in the instrument.
Note that `write()` does not return anything, you'd have to do `return self.ask("SYS:CONF:HARD?")` to get the reply, too.
Same below.

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        """Recall the instrument state from specified memory resgister.""",
```suggestion
        """Recall the instrument state from specified memory register.""",
```

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    recall = Instrument.setting(
This feels like an "action", so should be a method, not a property.

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    SAVE = Instrument.setting(
Same as recall.

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        """align all the circuits of the instrument.
this feels like an action. what happens when you do the get part (":CAL:ALL?") - what does that return?

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    auto_align = Instrument.control(
boolean property "auto_align_enabled"?

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    display = Instrument.setting(
display_enabled?

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        validator=strict_discrete_set,
A validator does not make sense for a measurement property.

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    recive_file = Instrument.measurement(
```suggestion
    receive_file = Instrument.measurement(
```

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    delet_file = Instrument.setting(
```suggestion
    delete_file = Instrument.setting(
```

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    delet_file = Instrument.setting(
but should be a method imo.

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    mesure_units = Instrument.control(
```suggestion
    measure_units = Instrument.control(
```
but maybe better "measurement_units"?

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +    #     self.write(f":TRAC TRACE{source})
should be deleted?

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        """ determine werther to sort peaks by frequency or amplitude""",
```suggestion
        """ determine whether to sort peaks by frequency or amplitude""",
```

2022-08-05 20:22 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        """ determine werther to sort peaks by frequency or amplitude""",
also below

2022-08-05 20:25 UTC, bilderbuchi commented on pymeasure/instruments/agilent/agilentE4407B.py
> +        """ Turn on or off the linear x10 gain stage in the quasi-peak and emi average detector only valid with the emi detector enabled.
```suggestion
        """ Turn on or off the linear x10 gain stage in the quasi-peak and emi average detector.
        
         Only valid with the emi detector enabled.
```

2025-06-27 08:15 UTC, closed without merging

2025-06-27 08:15 UTC, BenediktBurger commented
Closed due to lack of response. It might be reopened whenever there is interest.