Created Teledyne base classes with most of `LeCroyT3DSO1204` functionality
pymeasure/pymeasure pull request #951
Opened 2023-07-21 08:44 UTC by RobertoRoos

This PR is split of from my original: #868 
This in the progress of fixing #857 

Note: I also applied the patches on `LeCroyT3DSO1204` from March until now on the original file and the new Teledyne class. This diff can be viewed at: https://github.com/pymeasure/pymeasure/compare/9afd3c..41675c#diff-cc461e0399252211cf6d632e042fcbf0e4e7ae44b99f9550fad375e8ce360f4b

2023-07-21 10:03 UTC, bmoneke requested changes
A few comments, but I'm confident, we will merge it soon.

As this is your first PR which is going to be merged, you might include the authors.txt here as well.

As you clean the docstrings, you might remove the following lines, which allow the instrument to skip the docstring test.

https://github.com/pymeasure/pymeasure/blob/6ff994ee3c4a74ce641b61b4c955093de490980c/tests/instruments/test_all_instruments.py#L177

https://github.com/pymeasure/pymeasure/blob/6ff994ee3c4a74ce641b61b4c955093de490980c/tests/instruments/test_all_instruments.py#L207

2023-07-21 10:03 UTC, bmoneke commented on pymeasure/instruments/teledyne/teledyne_oscilloscope.py
> +        """ Writes the command to the instrument through the adapter.
Just a small thing, as we are touching the whole file:
```suggestion
        """ Write the command to the instrument through the adapter.
```
(docstrings should have their first phrase in imperative mode.)

2023-07-21 10:03 UTC, bmoneke commented on pymeasure/instruments/teledyne/teledyne_oscilloscope.py
> +        """Set the internal low-pass filter for all channels.
Is it really all channels? The command includes only a single channel in its name (from `insert_id`) and the instrument has a bwlimit command as well, which sets all channels.

Mabye a wrong copy paste from the wrong position?

2023-07-24 08:08 UTC, RobertoRoos commented on pymeasure/instruments/lecroy/lecroyT3DSO1204.py
>      bwlimit = Instrument.control(
Yeah, but I think the options were different for different oscilloscopes. I emphasized this in the doc.

2023-07-24 08:08 UTC, RobertoRoos commented on pymeasure/instruments/teledyne/teledyne_oscilloscope.py
> +    them.
Very basic base :p

2023-08-16 12:55 UTC, RobertoRoos commented
Oops, I had already forgotten about this...
@bmoneke can we merge?

2023-09-05 13:25 UTC, bmoneke commented
Sorry, I was on vacation.

2023-09-05 13:25 UTC, merged